title : mlcourse.ai bonus pack
author: Yury Kashnitsky (yorko)
logo: 'mlcourse_ai_logo_bonus.jpg'

# Short description about the book
description: >-
  Open Machine Learning course – Bonus assignments

execute:
  execute_notebooks           : cache
  run_in_temp: true
  timeout: -1

# exclude some content
exclude_patterns: [_static/data/*]

# HTML-specific settings
html:
  home_page_in_navbar         : true

# Interact link settings
notebook_interface            : "notebook"

# # Launch button settings
# repository:
#   url                         : https://github.com/executablebooks/quantecon-mini-example
#   path_to_book                : "mini_book"

# binder:
#   binderhub_url               : "https://mybinder.org"
#   text                        : "Launch binder"

# LaTeX settings
bibtex_bibfiles:
   - _bibliography/references.bib
latex:
  latex_engine                : "xelatex"
  latex_documents:
    targetname: book.tex

sphinx:
  config:
    html_extra_path: ['_static']
